### ISSUE TITLE
Hard Coded Imports

### ISSUE THREAD

**Issue by taalexander** [SchusterLab/GRAPE-Tensorflow-Examples#1]
Current imports of the [quantum-optimal-control](https://github.com/SchusterLab/quantum-optimal-control) library are hard-coded with respect to a specific directory structure. This is due to the current lack of installation method which is addressed by [#1](https://github.com/SchusterLab/quantum-optimal-control/issues/1).

**Comment by whitewhim2718** [comment]
Resolved in #4

**Comment by taalexander** [comment]
Resolved in #4
